MonkeyFinancesMVC/Models/ErrorViewModel.cs
namespace MonkeyFinancesMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MonkeyFinancesMVC/Models/HomeModel.cs
namespace MonkeyFinancesMVC.Models
{
    public class HomeModel
    {
        public string Name { get; set; } 

        public string Email { get; set; }

    }
}

MonkeyFinancesMVC/Models/LoginModel.cs
namespace MonkeyFinancesMVC.Models
{
    public class LoginModel
    {
        public string Email { get; set; }

        public string Senha { get; set; }
    }
}

MonkeyFinancesMVC/Models/RegistroModel.cs
namespace MonkeyFinancesMVC.Models
{
    public class RegistroModel
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        public double? Valor { get; set; }

        public string? Tipo { get; set; }
    }
}

MonkeyFinancesMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MonkeyFinancesMVC.Models;

namespace MonkeyFinancesMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MonkeyFinancesMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using MonkeyFinancesMVC.Models;

namespace MonkeyFinancesMVC.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Entrar(LoginModel loginModel)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    return RedirectToAction("Index", "Home");
                }
                return View("Index");
            }
            catch(Exception erro)
            {

                return RedirectToAction("Index");
            }
        }
    }
}

MonkeyFinancesMVC/Controllers/RegistroController.cs
using Microsoft.AspNetCore.Mvc;
using MonkeyFinancesMVC.Models;
using MonkeyFinancesMVC.Repositorio;

namespace MonkeyFinancesMVC.Controllers
{
    public class RegistroController : Controller
    {
        private readonly IRegistroRepositorio _registroRepositorio;

        public RegistroController(IRegistroRepositorio registroRepositorio)
        {
            _registroRepositorio = registroRepositorio;
        }

        public IActionResult Index()
        {
            List<RegistroModel> registro = _registroRepositorio.BuscarTodos();
            return View(registro);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            RegistroModel registro = _registroRepositorio.ListarPorId(id);
            return View(registro);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            RegistroModel registro = _registroRepositorio.ListarPorId(id);
            return View(registro);
        }
        
        public IActionResult Apagar(int id)
        {
            _registroRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(RegistroModel registro)
        {
            _registroRepositorio.Adicionar(registro);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(RegistroModel registro)
        {
            _registroRepositorio.Atualizar(registro);

            return RedirectToAction("Index");
        }


    }
}

MonkeyFinancesMVC/Views/Home - Cópia/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!</h1>
    <p>Sistema de registro Bancários</p>
</div>

MonkeyFinancesMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo!</h1>
    <p>Sistema de registro Bancários</p>
</div>

MonkeyFinancesMVC/Views/Login/Index.cshtml
@model LoginModel
@{
	Layout = "_LayoutDeslogado";
	ViewData["Title"] = "Login";
}

<div class="container align-self-center d-flex justify-content-center">
    <form asp-controller="Login" asp-action="Entrar" method="post" class="align-self-center">

        <div class="form-group">
            <label for="nome" class="form-label">Email</label>
            <input type="email" asp-for="Email" id="email" class="form-control" placeholder="Digite seu email">
        </div>

        <br />

        <div class="form-group">
            <label for="valor" class="form-label">Senha</label>
            <input type="password" asp-for="Senha" id="senha" class="form-control" placeholder="Digite sua senha">
        </div>

        <br />

        <br />
        <br />

        <button type="submit" class="btn btn-primary w-100">Entrar</button>
    </form>
</div>
 

MonkeyFinancesMVC/Views/Registro/ApagarConfirmacao.cshtml
@model RegistroModel
@{
    ViewData["Title"] = "Confirmar apagar o registro";
}

<div class="text-center">
    <h3>Realmente deseja apgar o Registro (@Model.Name)?</h3>
</div>


<a class="btn btn-primary w-100" asp-action="Index" asp-controller="Registro" role="button">Cancelar exclusão</a>
<br />
<br />
<a class="btn btn-danger w-100" asp-action="Apagar" asp-controller="Registro" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

MonkeyFinancesMVC/Views/Registro/Criar.cshtml
@model RegistroModel
@{
    ViewData["Title"] = "Cadastrar Registro";
}

<div class="text-center">
    <h1 class="display-4">Criar Registro</h1>
</div>

<form asp-controller="Registro" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Digite o nome do item">
    </div>

    <br />

    <div class="form-group">
        <label for="valor" class="form-label">Valor</label>
        <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor do item">
    </div>

    <br />

    <div class="form-group">
        <label for="tipo" class="form-label">Tipo</label>
        <input type="text" asp-for="Tipo" class="form-control" placeholder="Digite o tipo do item">
    </div>

    <br />
    <br />

    <button type="submit" class="btn btn-primary w-100">Adicionar</button>
    <br />
    <br />
    <a class="btn btn-secondary w-100" asp-controller="Registro" asp-action="Index" role="button">Voltar</a>
</form> 

MonkeyFinancesMVC/Views/Registro/Editar.cshtml
@model RegistroModel
@{
    ViewData["Title"] = "Editar Registro";
}

<div class="text-center">
    <h1 class="display-4">Editar Registro</h1>
</div>

<form asp-controller="Registro" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Digite o nome do item">
    </div>

    <br />

    <div class="form-group">
        <label for="valor" class="form-label">Valor</label>
        <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor do item">
    </div>

    <br />

    <div class="form-group">
        <label for="tipo" class="form-label">Tipo</label>
        <input type="text" asp-for="Tipo" class="form-control" placeholder="Digite o tipo do item">
    </div>

    <br />
    <br />

    <button type="submit" class="btn btn-primary w-100">Alterar</button>
    <br />
    <br />
    <a class="btn btn-secondary w-100" asp-controller="Registro" asp-action="Index" role="button">Voltar</a>
 
</form>

MonkeyFinancesMVC/Views/Registro/Index.cshtml
@model List<RegistroModel>
@{
    ViewData["Title"] = "Listagem de Registros";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Registro" asp-action="Criar">Adicionar novo Registro</a>
    </div>
    <br />

    <h1 class="display-4">Listagem de Registros</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Valor</th>
                <th scope="col">Tipo</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any()) {
                foreach(RegistroModel registro in Model){
                    <tr>
                        <th scope="row">@registro.Id</th>
                        <td>@registro.Name</td>
                        <td>@registro.Valor</td>
                        <td>@registro.Tipo</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@registro.Id" asp-controller="Registro" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@registro.Id" asp-controller="Registro" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

MonkeyFinancesMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonkeyFinancesMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MonkeyFinancesMVC.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MonkeyFinancesMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Principal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registro" asp-action="Index">Registros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MonkeyFinancesMVC 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MonkeyFinancesMVC/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonkeyFinancesMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MonkeyFinancesMVC.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MonkeyFinancesMVC 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>